### ISSUE TITLE
STT0023: STT annotation pipeline maintenance handover to Ganga

### ISSUE THREAD

**Issue by spsither** [OpenPecha/stt-documentation#20]
### Description
STT annotation pipeline maintenance by feeding in tasks for transcription.

### Completion Criteria
We have enough data for STT and annotation can be stopped.

---
### Subtasks
 - [x] Input more task in `stt.pecha.tools`
 - [x] Delete task when `stt.pecha.tools` becomes slow
 - [ ] Insert more stt_mv task for cleaning when stt_mv_ga group runs out of task.
 - [ ] Give a monthly report for QC team and MV team to Gade
 - [x] Combine dataset to update our [dataset on hf](https://huggingface.co/datasets/openpecha/tibetan_asr_data)
 - [ ] Train the  STT model with updated data
